language: 'php'

sudo: false

addons:
  apt:
    packages:
      - 'tidy'

matrix:
  include:
    - php: 5.6
      env: 'DB=MYSQL CORE_RELEASE=3.2'
    - php: 5.6
      env: 'DB=MYSQL PDO=1 CORE_RELEASE=3.2'

branches:
  only:
    - 'master'

before_script:
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
# These cause issues during tests.
#  - rm -r multisites
  - rm -r multisites-googleanalytics
# This causes issues with SS 3.2 during tests.
  - rm -r versionedfiles
# This causes issues with SS 3.2 and PHP 5.6 during tests.
  - rm -r display_logic

script:
  - vendor/bin/phpunit framework/tests
  - vendor/bin/phpunit framework/admin/tests
  - vendor/bin/phpunit cms/tests
