---
Name: sisconfigblocks
After: 'framework/*','cms/*'
Only:
  moduleexists: 'blocks'
---
Block:
  extensions:
    - ChangeRecordable
BlockSet:
  extensions:
    - ChangeRecordable
---
Name: sisconfigelemental
After: 'framework/*','cms/*'
Only:
  moduleexists: 'elemental'
---
ElementalArea:
  extensions:
    - ChangeRecordable
BaseElement:
  extensions:
    - ChangeRecordable
---
Name: sismultisitesconfig
After: 'framework/*','cms/*'
Only:
  moduleexists: 'multisites'
---
Block:
  extensions:
    - MultisitesAware
BlockSet:
  extensions:
    - MultisitesAware
HtmlEditorField_Toolbar:
  extensions:
    - MultisitesHtmlEditorField_ToolbarExtension
FileField:
  extensions:
    - MultisitesFileFieldExtension
---
Name: sisspamprotectionconfig
After: 'framework/*','cms/*'
---
FormSpamProtectionExtension:
  default_spam_protector: '\StudioBonito\SilverStripe\SpamProtection\Honeypot\SpamProtector\HoneypotSpamProtector'
UserDefinedForm:
  extensions:
    - BasisUserDefinedFormSpamProtectionExtension
UserForm:
  extensions:
    - BasisUserFormSpamProtectionExtension
Form:
  extensions:
    - BasisFormProtectionExtension
BasisFormProtectionExtension:
  controllers:
    - Page_Controller
---
Name: sisconfig
After: 'framework/*','cms/*'
---
AssetAdmin:
  extensions:
    - AssetAdminSyncFilesExtension
DBField:
  extensions:
   - RichLinksExtension
SiteTree:
  extensions:
    - SiteTreeTaxonomyExtension
    - MetadataExtension
    - PageThumbnailExtension
    - SiteTreeChangeRecordable
Site:
  extensions:
   - SISSite
Link:
  extensions:
    - LinkExtension
TaxonomyTerm:
  extensions:
   - BasisTaxonomyTermExtension
PaginatedList:
  extensions:
    - PaginatedListIterationExtension
MetadataField:
  extensions:
   - AGLSMetadataFieldExtension
File:
  extensions:
    - SISFileExtension
    - ChangeRecordable
GDBackend:
  default_quality: 90
Session:
  timeout: 3600
LeftAndMain:
  session_keepalive_ping: false
  menu_groups:
    Administration:
      - ReportAdmin
      - SecurityAdmin
      - DataChangeAdmin
      - QueuedJobsAdmin
      - TimedNoticeAdmin
      - AdvancedWorkflowAdmin
  extra_requirements_css:
    ba-sis/css/cms-custom.css:
      media: all
PasswordField:
  autocomplete: false
Security:
  login_recording: true
Member:
  lock_out_after_incorrect_logins: 5
  lock_out_delay_mins: 15
FusionService:
  custom_tag_types:
    TaxonomyTerm: 'Name'
UserDefinedForm_EmailRecipient:
  extensions:
    - 'UserDefinedFormEmailRecipientExtension'